metadata.format.version = "1.1"

[versions]

velocity = "3.3.0-SNAPSHOT"
paper = "1.20.2-R0.1-SNAPSHOT"

blossom = "2.1.0"
shadow = "8.1.1"
runtask = "2.3.1"

miniplaceholders = "3.0.0-SNAPSHOT"
adventure = "4.24.0"
adventurefabric = "5.10.1"

[libraries]

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-platform-fabric = { group = "net.kyori", name = "adventure-platform-fabric", version.ref = "adventurefabric" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.2" }
